name: "Pull Request Labeler"
on:
- pull_request_target

jobs:
  triage:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/labeler@main
      with:
        repo-token: "${{ secrets.GITHUB_TOKEN }}"
        
        # Add 'Direct-Plugin-Modifications' to any changes within 'example' folder or any subfolders
        Direct-Plugin-Modifications: /src/java/lukasbatema/mcje/plugin/*.java

        # Add 'Indirect-Plugin-Modifications' to any file changes within 'example2' folder
        Indirect-Plugin-Modifications: /plugin/*
